annotations:
  artifacthub.io/changes: |
     - "Use controller-v1.7.1"
  artifacthub.io/prerelease: "false"
apiVersion: v2
appVersion: 1.7.1
description: Ingress controller for Kubernetes using NGINX as a reverse proxy and
  load balancer
engine: gotpl
home: https://github.com/kubernetes/ingress-nginx
icon: https://upload.wikimedia.org/wikipedia/commons/thumb/c/c5/Nginx_logo.svg/500px-Nginx_logo.svg.png
keywords:
- ingress
- nginx
kubeVersion: '>=1.20.0-0'
maintainers:
- name: Pranjay Sagar
name: c3-nginx-ingress
sources:
  - https://ci-artifacts.c3.ai/v1/helm
type: application
version: 4.6.1-2
