annotations:
  artifacthub.io/changes: |
    - 'CI: Fix chart testing. (#12258)'
    - Update Ingress-Nginx version controller-v1.12.0
  artifacthub.io/prerelease: "false"
apiVersion: v2
appVersion: 1.12.0
description: Ingress controller for Kubernetes using NGINX as a reverse proxy and
  load balancer
home: https://github.com/kubernetes/ingress-nginx
icon: https://upload.wikimedia.org/wikipedia/commons/thumb/c/c5/Nginx_logo.svg/500px-Nginx_logo.svg.png
keywords:
- ingress
- nginx
kubeVersion: '>=1.21.0-0'
maintainers:
- name: Pranjay Sagar
- name: Chinmay Garg
name: c3-nginx-ingress
sources:
- https://ci-artifacts.c3.ai/v1/helm
version: 4.12.0
